services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_bot_api
    ports:
      - "8000:8000"
    # Автоматически загружает переменные из .env файла в корне проекта
    env_file:
      - .env
    restart: unless-stopped
    # Для разработки: монтируем код для автоперезагрузки
    # volumes:
    #   - .:/app