"""add users triggers

Revision ID: 3398e5014752
Revises: 16ac6f8233f1
Create Date: 2026-08-10 18:10:47.900812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '3398e5014752'
down_revision: Union[str, Sequence[str], None] = '16ac6f8233f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_assign_default_services_function = PGFunction(
        schema="public",
        signature="assign_default_services_function()",
        definition='RETURNS TRIGGER\n    AS $$\n    BEGIN\n        -- Фиксируем search_path для безопасности\n        SET search_path = public;\n\n        -- Создаем записи в user_services для нового пользователя со всеми активными сервисами\n        INSERT INTO public.user_services (user_id, service_id, config_data)\n        SELECT NEW.id, s.id, s.user_default_config_data\n        FROM public.services s\n        WHERE s.is_active is true\n        and s.is_blocked is false;\n\n        RETURN NEW;\n    END;\n    $$ LANGUAGE plpgsql'
    )
    op.create_entity(public_assign_default_services_function)

    public_users_trg_after_insert_users_assign_services = PGTrigger(
        schema="public",
        signature="trg_after_insert_users_assign_services",
        on_entity="public.users",
        is_constraint=False,
        definition='AFTER INSERT ON public.users FOR EACH ROW EXECUTE FUNCTION public.assign_default_services_function()'
    )
    op.create_entity(public_users_trg_after_insert_users_assign_services)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_users_trg_after_insert_users_assign_services = PGTrigger(
        schema="public",
        signature="trg_after_insert_users_assign_services",
        on_entity="public.users",
        is_constraint=False,
        definition='AFTER INSERT ON public.users FOR EACH ROW EXECUTE FUNCTION public.assign_default_services_function()'
    )
    op.drop_entity(public_users_trg_after_insert_users_assign_services)

    public_assign_default_services_function = PGFunction(
        schema="public",
        signature="assign_default_services_function()",
        definition='RETURNS TRIGGER\n    AS $$\n    BEGIN\n        -- Фиксируем search_path для безопасности\n        SET search_path = public;\n\n        -- Создаем записи в user_services для нового пользователя со всеми активными сервисами\n        INSERT INTO public.user_services (user_id, service_id, config_data)\n        SELECT NEW.id, s.id, s.user_default_config_data\n        FROM public.services s\n        WHERE s.is_active is true\n        and s.is_blocked is false;\n\n        RETURN NEW;\n    END;\n    $$ LANGUAGE plpgsql'
    )
    op.drop_entity(public_assign_default_services_function)

    # ### end Alembic commands ###
